version: "0.1.0"
services:
  project:
    restart: always
    container_name: code
    command : bash -c "uvicorn main:app --host 0.0.0.0 --port 80"
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - app-net

networks:
  app-net:
    driver: bridge